[build-system]
requires = ["setuptools", "wheel"]
build-backend = "backend"
backend-path = ["build_support"]

[tool.black]
target-version = ['py39']
extend-exclude = '''
(
  ^/arbeitszeit_flask/development_settings\.py |
  ^/arbeitszeit_flask/production_settings\.py |
  ^/arbeitszeit_flask/migrations/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
skip = "arbeitszeit_flask/migrations"

[tool.mypy]
files = [
    "arbeitszeit/**/*.py",
    "tests/**/*.py",
    "arbeitszeit_flask/__init__.py",
    "arbeitszeit_web/**/*.py"
]
mypy_path = "type_stubs"
exclude = '''
    migrations/
'''

[[tool.mypy.overrides]]
module = "arbeitszeit,arbeitszeit_web,arbeitszeit_flask,tests"
allow_untyped_defs = false

[[tool.mypy.overrides]]
module = "arbeitszeit_flask.*"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "tests.*"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "flask_babel",
    "flask_mail",
    "flask_migrate",
    "flask_sqlalchemy",
    "flask_talisman",
    "flask_wtf.*",
    "is_safe_url",
    "matplotlib.*",
    "sqlalchemy.*",
    "wtforms",
    "pytz"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = [
    '''ignore:'_app_ctx_stack' is deprecated:DeprecationWarning''',
    'ignore:Dialect sqlite\+pysqlite does \*not\* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur',
]