# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Arbeitszeitapp CI Tests

on:
  push:
    branches:
      - master
      - sebas/file-plan
  pull_request:
    branches:
      - master
      - sebas/file-plan

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - run: nix flake check --print-build-logs
    - run: nix build --print-build-logs
    # We don't need to run this unittests since they are run as part of 'nix build'
    - run: nix develop --command ./run-checks --no-unittests

  build-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
        cache: 'pip'
    
    - name: Install dependencies        
      run: |
        python -m venv ./venv && . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Test with ./run-checks
      run: |
        . ./venv/bin/activate
        ./run-checks
        deactivate

    - name: Try build developer documentation
      run: |
        . ./venv/bin/activate
        make html
        deactivate

