name: Arbeitszeitapp CI Tests

on: push

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: arbeitszeit
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --print-build-logs
    - run: nix build --print-build-logs
    - run: nix develop --command ./run-checks
      env:
        ARBEITSZEITAPP_TEST_DB: postgresql://postgres:postgres@localhost:5432/postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  build-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m venv ./venv && . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Test with ./run-checks
      run: |
        . ./venv/bin/activate
        ./run-checks
        deactivate
      env:
        ARBEITSZEITAPP_TEST_DB: postgresql://postgres:postgres@localhost:5432/postgres

    - name: Try build developer documentation
      run: |
        . ./venv/bin/activate
        make html
        deactivate
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  nixos-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: arbeitszeit
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop .#stable --command ./run-checks
      env:
        ARBEITSZEITAPP_TEST_DB: postgresql://postgres:postgres@localhost:5432/postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
