# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Arbeitszeitapp CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: ci

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Set up caching
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: ./venv/
        key: ${{ runner.os }}-env-${{ hashFiles('**/requirements*.txt') }}
    
    - name: Install dependencies        
      run: |
        python -m venv ./venv && . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install flake8 mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if: steps.cache-venv.outputs.cache-hit != 'true'
    
    - name: Test with ./run-checks
      run: . ./venv/bin/activate && ./run-checks
